services:
  spark-master:
    image: apache-spark:3.4.0
    container_name: spark-master
    ports:
      - "8080:8080" # Web UI Master
      - "7077:7077" # Spark Master Port
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

  spark-worker-a:
    image: apache-spark:3.4.0
    container_name: spark-worker-a
    ports:
      - "8081:8081" # Web UI Worker
      - "7001:7000" # Spark Worker Port
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

  spark-worker-b:
    image: apache-spark:3.4.0
    container_name: spark-worker-b
    ports:
      - "8082:8081" # Web UI Worker
      - "7002:7000" # Spark Worker Port
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
